### ISSUE TITLE
Unsupported syscall getrusage and prctl

### ISSUE THREAD

**Issue by yzz127** [gramineproject/gramine#1001]
### Description of the problem

When we ran a network related workload, we saw "Unsupported syscall" for both getrusage and prctl. We want to raise it to the community to see if they can be supported. As the workload is IP protected, we can not share the details to reproduce the issue, but attached a trace log that clearly shows the issues.

Please review, and thank you very much for any feedbacks!

### Actual results

warning: Unsupported system call getrusage
warning: Unsupported system call getrusage
trace: ---- gettimeofday(0x322a7d3f0, 0) = 0x0
trace: ---- set_robust_list(0x3223709e0, 0x18) = 0x0
trace: ---- gettimeofday(0x322a7d3f0, 0) = 0x0
trace: ---- mmap(0, 0x1001000, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0x0) ...
trace: ---- getpriority(0, 0) = 0x14
trace: ---- setpriority(0, 0, -10) = -13
trace: ---- write(2, 0x32236d7c0, 0x39) ...
unable to set thread nice value: Operation not permitted
trace: ---- return from write(...) = 0x39
warning: Unsupported system call prctl
trace: ---- nanosleep([0,500000000], 0) ...
trace: ---- return from mmap(...) = 0x32036f000
trace: ---- mprotect(0x32036f000, 0x1000, PROT_NONE) ...
trace: ---- return from mprotect(...) = 0x0

### Gramine commit hash

c1352166b8aa9dbe4c4fb4c531b6f1f707cd2c4b

**Comment by dimakuv** [comment]
Thanks for the report @yzz127. But does it break your application? It looks like the app just continues running fine.

All the mentioned system calls can **not** be implemented properly in Gramine:
- `getrusage` -- returns resource usage statistics, such as CPU time used and page faults. This stats is stored in the untrusted host Linux kernel, so Gramine cannot rely on Linux (it may return malicious values). Gramine also cannot keep stats on these resources (for example, page faults are completely transparent to the userspace apps, which Gramine is).
- `prctl` -- perform special operaitons on the process, mainly modifying capabilities. Gramine doesn't implement them, and there seems to be no sense in implementing any of them for Intel SGX.
- `setpriority` -- set scheduling priority. Gramine doesn't control thread/task scheduling, so this system call is useless. Gramine could forward the scheduling priority to the Linux kernel, but typically this produces only some minimal perf benefit, and generally doesn't seem to be useful for modern applications.

So, Gramine could theoretically implement these syscalls **in a dummy no-op way**. However, we haven't seen an application that would break because of Gramine currently doesn't implement them at all. And your example also shows that your application doesn't break.

So is there really anything to be done here?

**Comment by mkow** [comment]
Seems there's nothing to do here, closing.
