### ISSUE TITLE
[LibOS] `poll` syscall doesn't distinguish `POLLERR` and `POLLHUP` in `revents`

### ISSUE THREAD

**Issue by llly** [gramineproject/gramine#1034]
### Description of the problem

In `libos_syscall_poll` flow, Pal translates `revents` with any flag in `POLLHUP`, `POLLERR`, `POLLNVAL` to a single flag `PAL_WAIT_ERROR`.
https://github.com/gramineproject/gramine/blob/72f65247af61c55c54033c3c6934ed21b607987b/pal/src/host/linux-sgx/pal_object.c#L77-L80
LibOS translates `PAL_WAIT_ERROR` back to `POLLERR | POLLHUP`, it can be different from origin flag.
https://github.com/gramineproject/gramine/blob/72f65247af61c55c54033c3c6934ed21b607987b/libos/src/sys/libos_poll.c#L177-L178

A  Pytorch utility `TCPStoreWorkerDaemon` calls `poll` and expects the `revents` to have `POLLHUP`, but not `POLLERR`. Fortunately, it has completed work at that time.
https://github.com/pytorch/pytorch/blob/dcefea2706fb35ece5e49fc138d952a2acd15824/torch/csrc/distributed/c10d/TCPStore.cpp#L733-L734

### Steps to reproduce

Run a Pytorch script in Gramine
```
torch.distributed.init_process_group("gloo")
#do something
torch.distributed.destroy_process_group()
```

### Expected results

Successfully exit

### Actual results

Exception throwed `Unexpected poll revent on the control pipe's reading fd: 25: Software caused connection abort`.

### Gramine commit hash

e0ee62975d502dfab0c9236d7041bd5f45ce576d

**Comment by dimakuv** [comment]
Yes, this is a known problem. Originally Gramine tried to reduce the number of possible "erroneous" conditions reported from PAL to LibOS, that's why this multiplexing of 3 different Linux error conditions into a single `PAL_WAIT_ERROR`.

But this was bound to reach its limits. I'm actually surprised this multiplexing worked so well for so much time, and we found a real-world scenario where it fails only now :)

As for the solution, we must check what kind of errors are there in POSIX and Windows. If these 3 error conditions are in all OSes/standards, then we can "de-multiplex" them in our Gramine code.

**Comment by kailun-qin** [comment]
@dimakuv Pls assign this to me. Thanks!
