### ISSUE TITLE
[LibOS] Duplicate print when use `fork`

### ISSUE THREAD

**Issue by billionairiam** [gramineproject/gramine#1167]
### Description of the problem

I have noticed that Gramine repeats printing when using the `fork` function.

### Steps to reproduce

When running the following code
```
#include <stdio.h>
#include <unistd.h>
#include<sys/wait.h>

static void func1(int index, int count) {
    printf("[%d/%d func1 SUCCESS!]\n", index, count);

}

static void childfunc(int index, int count) {
    printf("[%d/%d func2 SUCCESS!]\n", index, count);
}

static void func2(int index, int count) {
    pid_t pid;
    pid = fork();
    if (pid == 0)
        childfunc(index, count);
    else {
        int status;
        wait(&status);
    }
}

int main(void) {
    func1(1,2);
    func2(2,2);
}
```
### Expected results

```
[1/2 func1 SUCCESS!]
[2/2 func2 SUCCESS!]
```

### Actual results

```
[1/2 func1 SUCCESS!]
[2/2 func2 SUCCESS!]
[1/2 func1 SUCCESS!]
```

### Gramine commit hash

5fb315426a3bcc306969d5ace203513265844c38

**Comment by dimakuv** [comment]
@billionairiam Yes, this is a known issue.

However, this issue is too insignificant to provide a proper fix for it. The full context can be found by reading these:
- https://github.com/gramineproject/graphene/issues/1212
- https://github.com/gramineproject/graphene/pull/1423
- https://github.com/gramineproject/graphene/issues/2091

A quick fix to this problem is to add these two lines in the manifest file: https://github.com/gramineproject/gramine/blob/5fb315426a3bcc306969d5ace203513265844c38/libos/test/ltp/manifest.template#L6-L7

Alternatively, if you can modify the source code itself, just add this: `setbuf(stdout, NULL);` at startup of your application.

**Comment by dimakuv** [comment]
I'll close this issue.

**Comment by mkow** [comment]
> Yes, this is a known issue.

No, this is _not_ an issue, this is how Linux works.

> Expected results
> ```
> [1/2 func1 SUCCESS!]
> [2/2 func2 SUCCESS!]
> ```

This is wrong. You're using `fork()` incorrectly and thus you get random results. `fork()` is a very low-level interface to the OS, normal programmers should never use it for anything (especially without understanding how it works).
