### ISSUE TITLE
gramine-test cannot found

### ISSUE THREAD

**Issue by Antone077** [gramineproject/gramine#1190]
### Description of the problem

I am able to install gramine. I can see all the tools

#( 02/20/23@ 3:44下午 )( hyk@hyk-a106 ):~/gramine    @master
  
  ```
 gramine-
   gramine-argv-serializer        gramine-sgx-gen-private-key    gramine-sgx-pf-tamper        
   gramine-direct                 gramine-sgx-get-token          gramine-sgx-quote-dump       
   gramine-gen-depend             gramine-sgx-ias-request        gramine-sgx-sign             
   gramine-manifest               gramine-sgx-ias-verify-report                               
   gramine-sgx                    gramine-sgx-pf-crypt 
```

However I don't see gramine-test . What do I need to do to install it? I am installing it in Ubuntu 22.04 kernel version 5.19.0-32-generic

### Steps to reproduce

- I install gramine with this Link（https://gramine.readthedocs.io/en/v1.4/quickstart.html#ubuntu-22-04-lts-20-04-lts-or-18-04-lts）.

- Then I want to test LTP(/gramine/libos/test/ltp),but when I run make command, it will report error (gramine-test not fouund).
```
touch /home/hyk/gramine/libos/test/ltp//install/INSTALL_SUCCESS
gramine-test build
make: gramine-test: 没有那个文件或目录
make: *** [Makefile:39：manifests] 错误 127
```

### Gramine commit hash

master

**Comment by dimakuv** [comment]
That's because `gramine-test` is **not** available in released Gramine packages.

`gramine-test` is a utility for testing, useful for Gramine developers but not for end users.

If you want to run some particular LTP program, then you should write a manifest file yourself and use the flows similar to the ones in CI-Examples (see any `Makefile` there).

If you want to run the LTP test suite under Gramine, then you need to build Gramine yourself: https://gramine.readthedocs.io/en/latest/devel/building.html

**Comment by Antone077** [comment]
@dimakuv OK,Thank you for your answer!
