### ISSUE TITLE
EDMM: Add support for dynamic thread creation

### ISSUE THREAD

**Issue by vijaydhanraj** [gramineproject/gramine#1223]
### Description of the feature

Each executing thread in the enclave is associated with a `Thread Control Structure (TCS)`. The `TCS` contains meta-data used by the hardware to save and restore thread specific information when entering/exiting the enclave.

The SGX2 extensions allow dynamically adding TCS page to an enclave there by providing capability to add/remove threads during enclave runtime and removes the hard limit of max threads that can be used in an enclave.

### Why Gramine should implement it?

Gramine could get away with this (https://gramine.readthedocs.io/en/stable/manifest-syntax.html#number-of-threads) hard limit on the number of threads that can run within an enclave

**Comment by llly** [comment]
I can work out the design and implement it if @vijaydhanraj doesn't have time for it.

**Comment by llly** [comment]
# Design proposal
Current Pal-SGX host prepares `sgx.max_threads` mumber of static SSA, TCS, TLS, stack, sig_stack before init enclave. It fills all static TCS page address to `g_enclave_thread_map`. When new host thread is created, Pal-SGX host uses `g_enclave_thread_map` to find available static TCS page and fails if no available static TCS pages. Then new host thread enters enclave using this static TCS page.

Here proposed that Pal-SGX enclave prepares and manages dynamic thread data: TCS, SSA, stack, sig_stack, TCB(same as TLS). When creating new thread, Pal-SGX enclave gets or allocates an available dynamic thread data and pass the TCS address to Pal-SGX host. Pal-SGX host choose to use this dynamic TCS for new thread to enter enclave If no available static TCS page, or a static TCS page if available.

# Changes:

- Add new `mem_mgr` in Pal-SGX enclave to allocate and manage dynamic thread data. The data is page-aligned struct of `TCS`, `SSA`, `stack`, `sig_stack` and `pal_enclave_tcb`.

- Add an enclave EDMM operation `sgx_edmm_convert_tcs_pages` to convert a regular page to TCS page. It utilizes current `ocall_edmm_modify_pages_type` and `sgx_eaccept` following [spec](https://www.intel.com/content/dam/develop/external/us/en/documents/329298-002-629101.pdf#page=43).

- `_PalThreadCreate` in Pal-SGX enclave gets free or allocates new dynamic thread data from dynamic thread data `mem_mgr`. When it's allocated, initialize all values and offsets then covert the TCS page.

- Update `int ocall_clone_thread(void)` to `int ocall_clone_thread(void* tcs)` and so do related interfaces in order to pass the dynamic TCS page address from enclave to host.

- Update `map_tcs`, `unmap_tcs` functions in Pal-SGX host , which manage `g_enclave_thread_map`. Extend `g_enclave_thread_map` to map both static and dynamic TCS page address.

- Update `pal_start_thread` in Pal-SGX enclave to check wether the dynamic TCS is used in current new thread. If dynamic TCS not used, release the dynamic TCS to `mem_mgr` before calling worload callback. Otherwise, release the dynamic TCS to `mem_mgr` after calling worload callback, before thread exit. 

This proposal doesn't alter control of TCS, or thread creation flow. If EDMM is not enabled, everything stays the same.

# Impacts:
manifest: No changes. `sgx.max_threads` became number of static thread data. When thread number exceeds `sgx.max_threads`, dynamic thread data will be used instead of error returned.

Debugger: It has a `MAX_DBG_THREADS 4096` limitation. Will not change it. I suppose users don't debug a workload with more than 4096 threads running at the same time.

Attached a flow chart of the proposal. 
![EDMM dynamic thread creation](https://user-images.githubusercontent.com/3078269/234196883-2f88332b-e29c-4fee-b720-b3e6945d68e5.png)

**Comment by dimakuv** [comment]
I'm unclear about the following aspects:

1. Why does `_PalThreadCreate()` always allocate a dynamic TCB? This in-enclave function also needs to decide whether to allocate the thread metadata (TCS, SSA, etc) from a static pool or from a dynamic pool (which in turn has two options: reuse the already-freed dynamic thread, or create a new thread using EDMM flows).
2. I don't understand what happens in the Host Child Thread -- the `dynamic tcs unreleased` box. What is it intended to do?

The rest looks good to me. If I understand correctly, we will **never free dynamically created threads**, but instead we will reuse them. This is the same as we do with in-enclave thread stacks on the Linux PAL, see: https://github.com/gramineproject/gramine/blob/a01265b22b20abe47f11968a2e35318866e5166f/pal/src/host/linux/pal_threading.c#L23-L73

Feel free to reuse some parts of that logic in your implementation for Linux-SGX.

**Comment by llly** [comment]
> I don't understand what happens in the Host Child Thread -- the dynamic tcs unreleased box. What is it intended to do?

TCS is really released after host calls EEXIT and then `unmap_tcs` from `g_enclave_thread_map`. Enclave thread releases the dynamic TCS metadata before TCS really released after EEXIT in host. So there is race condition, one thread is exiting, released TCS metadata and host hasn't call EEXIT, another thread creation reused the dynamic TCS. host `map_tcs` need to handle it.

> Why does _PalThreadCreate() always allocate a dynamic TCB?

The reason is similar to your second question, enclave doesn't know whether a TCS is released accurately. 
Enclave threading functions only manage dynamic TCS pool, allocate new or reuse free dynamic TCS. Enclave also tracking static TCS changes current behavior(without EDMM), for example, add a static TCS counter.  I can change the design if it's OK.

**Comment by dimakuv** [comment]
@llly presented the diagram above during today's Gramine meeting, and (at least to me) the design sounded correct.
