### ISSUE TITLE
Gramine is unable to look for libacl library present in /usr directory

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1228]
### Description of the problem

For some reason libacl library is under **/usr/lib/x86_64-linux-gnu/libacl.so.1 in Debian 11** whereas for **Ubuntu 18.04, 20.04 & 22.04 it is under /lib/x86_64-linux-gnu/libacl.so.1**

LTP test pipe2_02 need libacl.so.1

**Currently pipe2_02 has been disabled by Gramine but if we use attached manifest file we can run pipe2_02**
[pipe2_02.manifest.txt](https://github.com/gramineproject/gramine/files/10956214/pipe2_02.manifest.txt)

### Steps to reproduce

gramine-direct pipe2_02

Debug logs has been attached for both the OS

### Expected results

**Ubuntu:
gramine-direct pipe2_02**
[P1:T1:] error: Detected deprecated syntax: 'fs.mounts[0].path' ("etc") is not absolute. Consider converting it to absolute by adding "/" at the beginning.
[P1:T1:] error: Mounting file:/dev/cpu_dma_latency may expose unsanitized, unsafe files to unsuspecting application. Gramine will continue application execution, but this configuration is not recommended for use in production!
/home/intel/anjali/graphene_local_ci/gramine/libos/test/ltp/ltp_src/lib/tst_test.c:1362: TINFO: Timeout per run is 0h 05m 00s
/home/intel/anjali/graphene_local_ci/gramine/libos/test/ltp/ltp_src/testcases/kernel/syscalls/pipe2/pipe2_02.c:43: TPASS: test O_CLOEXEC for pipe2 success

Summary:
passed   0
failed   0
broken   0
skipped  0
warnings 0
[gramine_direct_pipe2_02_ubuntu.log](https://github.com/gramineproject/gramine/files/10956229/gramine_direct_pipe2_02_ubuntu.log)

### Actual results

**Debian:
gramine-direct pipe2_02**
[1.789] cp: error while loading shared libraries: libacl.so.1: cannot open shared object file: No such file or directory
[1.792] /home/intel/jenkins/workspace/nakul_sgx_debian/gramine/libos/test/ltp/ltp_src/lib/tst_test.c:804: TBROK: Failed to copy '//pipe2_02_child' to '.'
[1.792]
[1.792] Summary:
[1.792] passed   0
[1.792] failed   0
[1.792] broken   1
[1.792] skipped  0
[1.792] warnings 0

[gramine_direct_pipe2_02_debian.log](https://github.com/gramineproject/gramine/files/10956233/gramine_direct_pipe2_02_debian.log)

### Gramine commit hash

299dde8f4c96d7a0e2d2ef1652c5a241777607e7

**Comment by dimakuv** [comment]
Looking at the current manifest: https://github.com/gramineproject/gramine/blob/master/libos/test/ltp/manifest.template

I see that Gramine exposes both `/lib/x86_64-linux-gnu/` (via the `{{ arch_libdir }}` variable) and `/usr/` directories.

So technically both `/lib/x86_64-linux-gnu/libacl.so.1` and `/usr/lib/x86_64-linux-gnu/libacl.so.1` should be visible in LTP tests. But I also notice that we do **not** have the second directory in `LD_LIBRARY_PATH`: https://github.com/gramineproject/gramine/blob/d4ebd7e2501dcd8447debb96a938ea819c19148d/libos/test/ltp/manifest.template#L4

Could this be the problem? What happens if you modify this line as follows:
```
loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/{{ arch_libdir }}:/usr/lib:/usr/lib64"
```

If this fixes your issue, then you can submit a PR. My proposed change is trivially correct.

But please also check if maybe some other LTP tests will become enabled due to this fix?

**Comment by anjalirai-intel** [comment]
Yes, it does help. After adding /usr/{{ arch_libdir }} to LD_LIBRARY_PATH, it worked, 

We will analyze the LTP and get back to you if any test passes.

I am closing the issue.

**Comment by dimakuv** [comment]
Please also submit a PR!

**Comment by anjalirai-intel** [comment]
Done.
https://github.com/gramineproject/gramine/pull/1230
