### ISSUE TITLE
[python] gramine-manifest fails when parsing commented out lines that require defines/variables

### ISSUE THREAD

**Issue by svenkata9** [gramineproject/gramine#1380]
### Description of the problem

If you have a manifest template that has lines that require defines/variables to be passed as arguments to gramine-manifest, but commented out, gramine-manifest command fails during jinja render because the variables are applied even for the commented-out lines first before passing on to toml.

For example, if you don't have `-Dpythondistpath=...` as part of `gramine-manifest` command, having the following lines in the manifest template will make `gramine-manifest` fail:

```
# fs.mount.pydistpath.type = "chroot"
    # fs.mount.pydistpath.path = "{{ pythondistpath }}"
 # fs.mount.pydistpath.uri = "file:{{ pythondistpath }}"
```

### Steps to reproduce

Add the lines below to manifest template
```
# fs.mount.pydistpath.type = "chroot"
    # fs.mount.pydistpath.path = "{{ pythondistpath }}"
 # fs.mount.pydistpath.uri = "file:{{ pythondistpath }}"
```

Build the manifest with `gramine-manifest` but without passing `-Dpythondistpath=...`

### Expected results

`gramine-manifest` should succeed even when there are lines requiring variables to be defined, but commented out.

### Actual results

```
gramine-manifest \
        -Dlog_level=error \
        -Darch_libdir=/lib/x86_64-linux-gnu \
        -Dentrypoint=/usr/bin/python3.10 \
        -Dra_type=none \
        -Dra_client_spid= \
        -Dra_client_linkable=0 \
        python.manifest.template >python.manifest
Traceback (most recent call last):
  File "/home/svenkat9/dev/s9/gramine/ginstall/bin/gramine-manifest", line 33, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/lib/python3/dist-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/svenkat9/dev/s9/gramine/ginstall/bin/gramine-manifest", line 29, in main
    manifest = Manifest.from_template(template, define)
  File "/home/svenkat9/dev/s9/gramine/ginstall/lib/python3.10/site-packages/graminelibos/manifest.py", line 148, in from_template
    return cls(_env.from_string(template).render(**(variables or {})))
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 20, in top-level template code
jinja2.exceptions.UndefinedError: 'pythondistpath' is undefined
make: *** [Makefile:20: python.manifest] Error 1
```

### Gramine commit hash

37550e191ccba4177f2975e4c09713f044980b08

**Comment by dimakuv** [comment]
This is indeed a problem.

Google gives many hits with questions how to solve this, e.g. https://github.com/saltstack/salt/issues/6450.

Unfortunately, there is no good way... This is because Jinja rendering runs *before* TOML rendering, and Jinja doesn't know about that other (TOML) syntax of the file, and there is no official way to tell Jinja about this.

I initially thought that we could first run the TOML parser, just to get rid of comments, but this will present another failure: TOML parser doesn't know about Jinja formatting, so when TOML tries to parse snippets like this: https://github.com/gramineproject/gramine/blob/37550e191ccba4177f2975e4c09713f044980b08/CI-Examples/python/python.manifest.template#L23-L25

the TOML parser will fail.

We have a chicken-and-egg problem here. Jinja doesn't know about TOML, and thus fails on e.g. TOML comments. And TOML doesn't know about Jinja, and thus fails on e.g. Jinja code blocks.

@woju Is there any way out of this recursion?

**Comment by mkow** [comment]
I think we've already had exactly this discussion in the past?

> This is indeed a problem.

I don't agree, this is the intended behavior, although not very intuitive. Some ideas how to make it a bit more obvious:
- Use file extensions properly (they should indicate the data format) and have `manifest.toml.jinja` which should be templated into `manifest.toml` by our scripts by default. This way when users are editing a `.jinja` file they would be reminded that it's a Jinja file, not a TOML file.
- Add a reminder about this in the documentation.

IMO we should do both.

> I initially thought that we could first run the TOML parser, just to get rid of comments, but this will present another failure: TOML parser doesn't know about Jinja formatting, so when TOML tries to parse snippets like this: [...]

Please don't, this is a terrible hack, while the solution it to simply use Jinja comments instead of TOML comments if you don't want Jinja to interpret the data.

**Comment by woju** [comment]
Oh, and we can also rewrite all example manifest to use jinja comments, if we run them through `gramine-manifest`. That would also help.

**Comment by dimakuv** [comment]
Yeah, I think the combination of (a) `.toml.jinja`, (b) explanation in the documentation, and (c) rewriting example manifests with Jinja style would solve such confusions.

On the other hand, and this is just thinking out loud, couldn't Jinja engine be augmented to optionally understand comments in popular formats (like YAML, TOML, etc.)? Having two styles of comments is crazy... And Jinja could have some plugins for popular use cases. (Or maybe this problem is generally intractable?)

**Comment by woju** [comment]
There are too many corner cases for it to be possible to solve using two distinct parsers. You might be able to solve this using a single, stateful parser with heavy coupling between the two or more layers, TeX-style. TeX' parser is the reason why people don't want to know things below LaTeX or other format, the error messages are cryptic, and random tracebacks can't be debugged by a person who just started writing his/her first article.

Basically you'll gain nothing, because instead of understanding TOML and jinja, one markup at a time, you'd need to understand the whole stack at once. Many people were put off plain TeX macros by this requirement. I don't want such a monstrosity in Gramine, and I'm willing to accept that some people will stumble on this minor inconvenience. And this problem is not specific to us, it's what generally happens when you stack two different markups, not least in DevOps world of those config frameworks like salt you've cited, where this problem is known and understood. Coincidentally, Gramine manifests should probably be written by DevOps people.

**Comment by mkow** [comment]
> On the other hand, and this is just thinking out loud, couldn't Jinja engine be augmented to optionally understand comments in popular formats (like YAML, TOML, etc.)? Having two styles of comments is crazy... And Jinja could have some plugins for popular use cases. (Or maybe this problem is generally intractable?)

No. How would you even define the grammar for such a thing? How should this be interpreted?

```Jinja
x = """
# {{X}}
"""
```

And then, what about this?

```Jinja
x = {{'"""'}}
# {{X}}
"""
```

etc.

You can't just smash a few different grammars together and parse them _at the same time_.

**Comment by mkow** [comment]
I extracted the file extension proposal to https://github.com/gramineproject/gramine/issues/1384.
