### ISSUE TITLE
Gramine doesn't propagate changes to a mmaped encrypted file back to the memory

### ISSUE THREAD

**Issue by haraldh** [gramineproject/gramine#1432]
### Description of the problem

Gramine does not propagate changes to a mmaped file back to the memory.

### Steps to reproduce

Reduced the problem to this small testcase: https://github.com/haraldh/shmem-test

### Expected results

```
[PASS] No errors detected.
```

### Actual results

```
Detected 100 times (100.000%) when file contents were incorrect.
Detected 100 times (100.000%) when mapping was incorrect.
```

### Gramine commit hash

v1.4

**Comment by haraldh** [comment]
seems like:
```diff
diff --git a/main.c b/main.c
index a8ea57d..4a7559c 100644
--- a/main.c
+++ b/main.c
@@ -102,6 +102,7 @@ int main(int argc, char *argv[]) {
         map[1] = (long) (~n);
 
         msync(map, 2 * sizeof map[0], MAP_SYNC);
+        fdatasync(fd);
 
         /* Check the file contents. */
         if (read_from(fd, data, sizeof data, 0)) {
```

reduces the problem to:
```
Detected 100 times (100.000%) when mapping was incorrect.
```

**Comment by dimakuv** [comment]
From a very quick look: indeed, looks like a bug in protected files implementation. It feels like there is some cache incoherence. (Protected files are cached in 64K chunks inside enclave memory, for performance reasons.)

Thanks for reporting this bug. Hopefully we'll find time to analyze this at some point.

**Comment by mkow** [comment]
Hmm, I think we just don't support concurrently editing a protected/encrypted file on disk and operating on it in the memory. Supporting this securely and without huge perf impact would be really hard I think.

**Comment by dimakuv** [comment]
> Hmm, I think we just don't support concurrently editing a protected/encrypted file on disk and operating on it in the memory. Supporting this securely and without huge perf impact would be really hard I think.

What do you mean? The file is **not** edited on disk. It's edited by the same program (Gramine app), just both with mmap read/write accesses and classic read/write syscalls.

**Comment by mkow** [comment]
Ahh, sorry, I misread the discussion then. Yeah, this looks like a bug.

**Comment by kailun-qin** [comment]
I looked a bit in the test case and the reported issue. Pls see my notes below.

1. The "incorrect file content" was simply caused by that in the test case, `msync(map, 2 * sizeof map[0], MAP_SYNC)` used an invalid flag of `msync()` (see https://github.com/haraldh/shmem-test/blob/d7ee6880a2c156bd8e73fd287a3f491962d6a1bf/main.c#L104), which should be `MS_SYNC`. The return value of `msync()` was not checked, i.e., it should've actually failed in this case. I submitted https://github.com/gramineproject/gramine/pull/1491 so that this can be inspected from logs more easily.
2. Due to 1), adding `fdatasync()` after (the failed) `msync()` which'll synchronize and flush the mapping (see: https://github.com/gramineproject/gramine/blob/92636ae0bc8187d48dd40536d2a1901cb8eb6cd6/libos/src/sys/libos_open.c#L492 and https://github.com/gramineproject/gramine/blob/92636ae0bc8187d48dd40536d2a1901cb8eb6cd6/libos/src/fs/chroot/encrypted.c#L381-L382) would then reduce the problem.
3. The "incorrect mapping" happened in the following conditions:
    1) The test case first wrote data to the encrypted file (see https://github.com/haraldh/shmem-test/blob/d7ee6880a2c156bd8e73fd287a3f491962d6a1bf/main.c#L50), which was not flushed (due to the mentioned in-enclave cache of encrypted files).
    2) Then on one hand, for encrypted-file-backed mappings, there was no synchronization happened after `write()` so the mapping was not updated; on the other hand, a subsequent `fdatasync()` (see https://github.com/haraldh/shmem-test/blob/d7ee6880a2c156bd8e73fd287a3f491962d6a1bf/main.c#L59) would even overwrite the cached data and flush w/ the stale mapping.
    3) The test case compared the (stale) mapping w/ the written data (https://github.com/haraldh/shmem-test/blob/d7ee6880a2c156bd8e73fd287a3f491962d6a1bf/main.c#L126), which should be the cause of the inconsistency.

**Comment by haraldh** [comment]
Ok, so by my understanding gramine needs a sync happening after `write()`. Correct?

**Comment by haraldh** [comment]
The problem origins from https://github.com/etcd-io/bbolt where they use the technique to write data via `write()` and read the data via mmaped memory. I guess they want to avoid to do `ftruncate` in case the file has to grow, which I did as an intermediate hotfix here: https://github.com/haraldh/bbolt/commit/6edf7e383aebc35d5669ec6bcec43f7014c2cfc6
