### ISSUE TITLE
Maximum enclave size

### ISSUE THREAD

**Issue by arkish** [gramineproject/gramine#1441]
I came across the suggestions in "performance tuning and Analysis" doc to increase enclave size as sgx.enclave_size = "512M", sgx.enclave_size = "1G", sgx.enclave_size = "2G" in cases of failure or complaints. I want to know, Does sgx.enclave_size represent maximum supported enclave size for Intel SGX? If so, can it be assigned values like "1G" and "2G" as given in documentation? Isn't the  maximum supported enclave size for Intel SGX 128MB? Please let me know if my understanding is incorrect. Thanks.

**Comment by dimakuv** [comment]
> Does sgx.enclave_size represent maximum supported enclave size for Intel SGX?

No. `sgx.enclave_size` represents **virtual memory** devoted for SGX-enclave data. Since virtual memory is, well, virtual, one can assign arbitrarily large value. I've seen people setting it to 1TB and more.

> Isn't the maximum supported enclave size for Intel SGX 128MB?

No. First of all, here you're implying **physical memory**, i.e., the amount of so-called EPC (which is a part of PRM) memory that is located on your machine. Second of all, modern Intel CPUs have much more than 128MB of EPC, up to 100s of GBs.

Overall, you can search for "physical vs virtual memory" if you're not familiar with these concepts. If you're familiar with these concepts, then always think of SGX-application memory as SGX virtual memory, and the actual backing SGX-driver memory as SGX physical memory. (How the SGX driver multiplexes SGX virtual memory to SGX physical memory is largely unimportant for us, application developers.)

**Comment by dimakuv** [comment]
> Is it possible to know how much enclave memory was consumed(in MB) by a particular application/script running in sgx using performance statistics(by setting sgx.enable_stats = true) ?

No, unfortunately perf stats that will appear on application termination are not available.

But if you're writing your application, you can at any point read the ``/proc/[pid]/status` file, and in the output of this file you'll find `VmPeak` which will give you the max enclave memory consumed.

See also:
- https://github.com/gramineproject/gramine/discussions/1086
- https://github.com/gramineproject/gramine/issues/614

**Comment by mkow** [comment]
Please don't use GitHub issues for general support (see the information in the issue template), we use issues to keep track of bugs in Gramine. If you need support then either:
- use GitHub Discussions,
- ask on our Gitter (https://gitter.im/gramineproject/community),
- or send an email to users@gramineproject.io.
