### ISSUE TITLE
`gramine-manifest`: do not set default `sgx.trusted_files`

### ISSUE THREAD

**Issue by mythi** [gramineproject/gramine#1518]
### Description of the feature

 (feel free to move this to Discussions first if the use-case needs clarifications)

I'm currently exploring a use-case based on:

"The manifest writer may also specify the hash for a file using the TOML-table syntax, in the field `sha256`; in this case, hashing of the file will be skipped by the signer tool and the value in `sha256` field will be used instead."

where my flow is:
1. run `gramine-manifest` for my template
2. `"cat <my-app-trusted-files-source>" >> <my-app>.manifest`
3. `gramine-sgx-sign`

currently, step 3. triggers an error:

```
  File "/usr/lib/python3/dist-packages/tomli/_parser.py", line 308, in create_list_rule
    raise suffixed_err(src, pos, f"Cannot mutate immutable namespace {key}")
tomli.TOMLDecodeError: Cannot mutate immutable namespace ('sgx', 'trusted_files') (at line 40, column 20)
```

because step 1. initializes an empty `sgx.trusted_files` array (so after 2, I have two such arrays). I can easily workaround it by, e.g., `sed`ing my manifest before step 2. (or 3.) to remove it but I was thinking if there was a way to do without custom hacks. My TOML knowledge is limited but it looks it's not possible to have any "empty" value in my template to overcome this?

### Why Gramine should implement it?

To allow users to sign apps where `sgx.trusted_files` are produced "out of band" per the use case described in Gramine manifest documentation.

**Comment by dimakuv** [comment]
The TOML spec doesn't allow to have duplicate keys. So your error is expected.

I'm not sure what you're proposing. But I think there are two clean ways to fix your problem:
1. Swap steps 1 and 2 places. In other words, the list `<my-app-trusted-files-source>` will be added to the manifest template, not to the already-generated manifest.
2. If you can't swap steps, then you are destined to inventing hacks, because the output of `gramine-manifest` is not supposed to be modified. So I would propose a hack smth like this before your step 2:
```bash
python3 -c "
import tomli, tomli_w
manifest = tomli.load(<file>)
try:
    del manifest['sgx']['trusted_files']
    tomli_w.dump(<same-file>)
except:
    pass
"
```

**Comment by mythi** [comment]
> I'm not sure what you're proposing. But I think there are two clean ways to fix your problem:

does `gramine-manifest` have to add `trusted_files = []` if the source template does not have any trusted files specified?

Swapping steps works but I was thinking of keeping the flow the same as what is commonly used today (sgx trusted files are hashed after the manifest is built). this way it's still possible to not run the hashing flow if only non-sgx manifest is needed.

**Comment by mkow** [comment]
@mythi: The problem here is that you're trying to modify a TOML config file with `cat` instead of a proper parser :) I'd just use a similar snippet to what @dimakuv suggested, but instead of deleting the table just add the entries you want.

> does `gramine-manifest` have to add `trusted_files = []` if the source template does not have any trusted files specified?

We could do this, but I don't want to keep this as an interface, sounds really brittle. I.e. I don't want users to rely on this behavior.

**Comment by mythi** [comment]
@mkow @dimakuv thanks for the feedback. I will think about my options and I'm not blocked by anything right now.
