### ISSUE TITLE
Workloads are failing with error to enable 'sgx.use_exinfo' in the manifest

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1561]
### Description of the problem

**Issue 1:**
In today's nightly we see few failures across the board for SGX pipelines in non-EDMM mode with "**error: Tried to handle a memory fault with no faulting address reported by SGX. Please consider enabling 'sgx.use_exinfo' in the manifest.**"

These workloads are running in non-EDMM mode so they don't require this flag

**Failed Workloads:**
examples -> Openjdk
Stress-ng -> Interrupt
LTP -> setrlimit01

**Issue 2:**
In EDMM pipeline also we see failures with same error "**Tried to handle a memory fault with no faulting address reported by SGX. Please consider enabling 'sgx.use_exinfo' in the manifest.**"

Previously below workloads were passing without throwing any error

**Failed Workloads:**
LTP -> setrlimit01, mmap03

### Steps to reproduce

To repro Issue 1:
Run openjdk workload from examples repo

To repro Issue 2:
Run LTP examples setrlimit01, mmap03

### Expected results
```
 gramine-sgx java MultiThreadMain
+ tee OUTPUT
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Final Count is: 10000
```
### Actual results
```
gramine-sgx java MultiThreadMain
+ tee OUTPUT
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

error: Tried to handle a memory fault with no faulting address reported by SGX. Please consider enabling 'sgx.use_exinfo' in the manifest.
```
### Gramine commit hash

12bd9f01165666804feb24e61a8ded840b43a53a

**Comment by anjalirai-intel** [comment]
@kailun-qin I don't think #1562 fixes the issue. 

The issue describes 2 cases, one with EDMM and one without EDMM.

These workloads were running successfully earlier for EDMM without this flag

**Comment by kailun-qin** [comment]
Thanks for the report!

> I don't think https://github.com/gramineproject/gramine/pull/1562 fixes the issue.
> The issue describes 2 cases, one with EDMM and one without EDMM.

Pls see my comments below.

For issue 1 (w/o EDMM), I suppose that the failures were expected.

We came to the conclusion in https://github.com/gramineproject/gramine/pull/1502 that Gramine should refuse working on workloads that require memfault handling but have `sgx.use_exinfo` not set in the manifest or the environment does not support EXINFO at all. This is for the sane and safe default behavior of Gramine, as well as for some security reasons. Pls see the summary how we came to this conclusion here: https://github.com/gramineproject/gramine/pull/1502#issuecomment-1712958476.

Note that for `Stress-ng -> Interrupt`, there is a "sigsegv stressor options" (pls see: https://github.com/ColinIanKing/stress-ng/blob/313566c1acc928a9bd24490c34451f5bb30f3f92/example-jobs/interrupt.job#L176-L182). I think you could try to disable it so that the other stressors in this job can continue to be executed.

> For 2nd issue workloads were running successfully earlier for EDMM without this flag

For issue 2 (w/ EDMM), the LTP tests were working simply because previously Linux-SGX PAL propagated the memory fault exception with address 0 anyway to LibOS/app even if no faulting address was actually reported by SGX (due to no `sgx.use_exinfo` set). Pls find some detailed analysis here: https://github.com/gramineproject/gramine/pull/1502#pullrequestreview-1618679625. This was not right and was exactly https://github.com/gramineproject/gramine/pull/1502 trying to address.

**Comment by anjalirai-intel** [comment]
> Thanks for the report!
> 
> > I don't think #1562 fixes the issue.
> > The issue describes 2 cases, one with EDMM and one without EDMM.
> 
> Pls see my comments below.
> 
> For issue 1 (w/o EDMM), I suppose that the failures were expected.
> 
> We came to the conclusion in #1502 that Gramine should refuse working on workloads that require memfault handling but have `sgx.use_exinfo` not set in the manifest or the environment does not support EXINFO at all. This is for the sane and safe default behavior of Gramine, as well as for some security reasons. Pls see the summary how we came to this conclusion here: [#1502 (comment)](https://github.com/gramineproject/gramine/pull/1502#issuecomment-1712958476).
> 
> Note that for `Stress-ng -> Interrupt`, there is a "sigsegv stressor options" (pls see: https://github.com/ColinIanKing/stress-ng/blob/313566c1acc928a9bd24490c34451f5bb30f3f92/example-jobs/interrupt.job#L176-L182). I think you could try to disable it so that the other stressors in this job can continue to be executed.
> 
> > For 2nd issue workloads were running successfully earlier for EDMM without this flag
> 
> For issue 2 (w/ EDMM), the LTP tests were working simply because previously Linux-SGX PAL propagated the memory fault exception with address 0 anyway to LibOS/app even if no faulting address was actually reported by SGX (due to no `sgx.use_exinfo` set). Pls find some detailed analysis here: [#1502 (review)](https://github.com/gramineproject/gramine/pull/1502#pullrequestreview-1618679625). This was not right and was exactly #1502 trying to address.

Thanks for the clarification

**Comment by anjalirai-intel** [comment]
The openjdk workload in examples repo will not work from now on without EDMM flag. Is that something okay?

**Comment by kailun-qin** [comment]
> The openjdk workload in examples repo will not work from now on without EDMM flag. Is that something okay?

I submmited https://github.com/gramineproject/examples/pull/79 for running it w/o EDMM flag but having EXINFO support.

**Comment by dimakuv** [comment]
I think in all such cases we must add an explicit unconditional `sgx.use_exinfo = true` into manifests.

This has a drawback that such workloads won't work on older Intel CPUs (before ~2017), but I think it's reasonable to require better-security CPUs rather than dragging less-secure configurations of SGX apps.
