### ISSUE TITLE
Post host-name change in system, gramine-sgx verification of hostname gets failed

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1626]
### Description of the problem

Recently, we had to change the hostname for one system, post that libos test `hostname_extra_runtime_conf` started failing for `gramine-sgx`. The test is working natively in `linux` and also for `gramine-direct`. 

**System Details:**
```
$ cat /etc/hostname 
rhel8_dev_gramine

$ hostnamectl status
   Static hostname: rhel8_dev_gramine
         Icon name: computer-server
           Chassis: server
```

### Steps to reproduce

1. cd libos/test/regression
2. gramine-test --sgx build hostname_extra_runtime_conf
3. gramine-direct hostname_extra_runtime_conf rhel8_dev_gramine
4. gramine-sgx hostname_extra_runtime_conf rhel8_dev_gramine

Logs:
[hostname_extra_direct.log](https://github.com/gramineproject/gramine/files/13176990/hostname_extra_direct.log)
[hostname_extra_sgx.log](https://github.com/gramineproject/gramine/files/13176991/hostname_extra_sgx.log)

### Expected results

```
$ gramine-direct hostname_extra_runtime_conf rhel8_dev_gramine
TEST OK

$ gramine-sgx hostname_extra_runtime_conf rhel8_dev_gramine
TEST OK
```

### Actual results

```
$ gramine-direct hostname_extra_runtime_conf rhel8_dev_gramine
TEST OK

$ gramine-sgx hostname_extra_runtime_conf rhel8_dev_gramine
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

hostname: gethostname: result doesn't match hostname (expected: rhel8_dev_gramine, got: localhost)
```

### Gramine commit hash

53a017831e70f491da0a8557f0094495dab7dac1

**Comment by kailun-qin** [comment]
I guess this is simply because `rhel8_dev_gramine` is not considered as a valid hostname by Gramine (the hostname contains '_', i.e., not only alphanumeric characters, '-', and '.'). Pls see: https://github.com/gramineproject/gramine/blob/53a017831e70f491da0a8557f0094495dab7dac1/pal/src/host/linux-sgx/pal_main.c#L277-L289.

BTW, pls note that the warning here: https://github.com/gramineproject/gramine/blob/53a017831e70f491da0a8557f0094495dab7dac1/pal/src/host/linux-sgx/pal_main.c#L366-L369 is not reflected in the trace log because we configure our logging system too late: https://github.com/gramineproject/gramine/blob/53a017831e70f491da0a8557f0094495dab7dac1/pal/src/pal_main.c#L388.

@anjalirai-intel Would you pls try changing: https://github.com/gramineproject/gramine/blob/53a017831e70f491da0a8557f0094495dab7dac1/pal/src/host/linux-sgx/pal_main.c#L367 into `log_always()`, re-build and run on your system and confirm this? Thanks!

I suggest that we configure logging as early as possibly (probably once after we init the slab manager). WDYT? @mkow @dimakuv

**Comment by mkow** [comment]
> I suggest that we configure logging as early as possibly (probably once after we init the slab manager). WDYT? @mkow @dimakuv

Sure, but I think there was a reason why we couldn't move it earlier? It requires at least relocations, but I'm not sure what more... But if it's possible then yes, it should happen quite early.

**Comment by anjalirai-intel** [comment]
@kailun-qin Why this restriction is only there for SGX but not for Direct

**Comment by dimakuv** [comment]
First of all, @kailun-qin is exactly correct with his analysis. The hostname `rhel8_dev_gramine` is not allowed by the standards. Check "ASSUMPTIONS" in https://datatracker.ietf.org/doc/html/rfc952.

> Why this restriction is only there for SGX but not for Direct

@anjalirai-intel Because `gramine-direct` doesn't care about security, and SGX cares about it. Having a bad name for the host is Ok in terms of functionality, but a no-no in terms of security (as it violates the standard).

> I suggest that we configure logging as early as possibly (probably once after we init the slab manager). WDYT? @mkow @dimakuv

No, please don't do it.

We have a common logic in `pal/src/pal_main.c`. We don't want to duplicate this logic for each PAL. That's why that logging configuration is done in the common logic -- to avoid duplication. And the common logic executes after the PAL-specific logic, which I think is also fair.

We created `post_callback()` exactly for this reason -- to print stuff **after** logging is configured. See https://github.com/gramineproject/gramine/blob/53a017831e70f491da0a8557f0094495dab7dac1/pal/src/host/linux-sgx/pal_main.c#L546-L553

So the correct fix for this is to somehow save the information about bad domain names/hostnames, and print the warnings in `post_callback()`.

**Comment by dimakuv** [comment]
@kailun-qin @mkow Alternatively, we can change `log_warning()` messages there to `log_error()` messages.

**Comment by anjalirai-intel** [comment]
@dimakuv So, we should change hostname back to something else following standards

**Comment by dimakuv** [comment]
@anjalirai-intel Yes. Just replace underscores (`_`) with dashes (`-`)

**Comment by anjalirai-intel** [comment]
@dimakuv @kailun-qin After changing the hostname, the test passes

**Comment by mkow** [comment]
> So the correct fix for this is to somehow save the information about bad domain names/hostnames, and print the warnings in `post_callback()`.

> Alternatively, we can change `log_warning()` messages there to `log_error()` messages.

Both sound good to me.

**Comment by kailun-qin** [comment]
> So the correct fix for this is to somehow save the information about bad domain names/hostnames, and print the warnings in post_callback().

> Alternatively, we can change log_warning() messages there to log_error() messages.

I picked the first approach since Gramine defines `error` log level as "a serious error preventing Gramine from operating properly (for example, error initializing one of the components)" while `warning` for "a non-fatal issue; might mean that application is requesting something unsupported or poorly emulated" (pls see: https://gramine.readthedocs.io/en/stable/manifest-syntax.html#log-level) -- so changing from `log_warning()` to `log_error()` seems to be not that appropriate in this case (where Graminie continues the execution after sanitization).
