### ISSUE TITLE
Concurrent EPC allocation when using EDMM

### ISSUE THREAD

**Issue by jakdurider** [gramineproject/gramine#1647]
### Description of the feature

I am running several application using gramine on SGX2-enabled machine, and I found it takes too much time to allocate new pages one by one. 
I guess that adding new EPC pages into same enclave is possible if each page is allocated with different virtual address. Anyone knows about this in detail?
Or anyone know whether adding two separate EPC pages into same enclave concurrently is possible or not?

### Why Gramine should implement it?

For enhancing performance

**Comment by dimakuv** [comment]
This "batching" of enclave pages during allocation/deallocation must be supported by the Intel SGX Linux driver. Otherwise Gramine can't do much -- even if Gramine would issue 2 concurrent allocation requests, they still each work on a single 4KB enclave page, and the overhead stems from several OCALLs and IOCTLs required for each enclave page allocation.

In other words, the current API (the IOCTL interface) supported by Linux's SGX EDMM driver is severely restricted to **a single enclave page allocation** per user-space request.

Unfortunately, to the best of my knowledge there is **no** support for batching in the Linux SGX driver.

**Comment by mkow** [comment]
Closing, as there's nothing on our side to do here.
We'll use a faster interface if it ever appears, but right now we can't do better.

**Comment by monavij** [comment]
@jakdurider You should request this feature in Linux SGX driver if its important for you.
