### ISSUE TITLE
Doc: When will the command is_sgx_available become available?

### ISSUE THREAD

**Issue by mkbhanda** [gramineproject/gramine#204]
## Description of the problem
in the quick start guide at https://graphene.readthedocs.io/en/latest/quickstart.html
is_sgx_available is alluded to test if SGX is available. Thyat appears to be a command that will become available only after a successful build.
Perhaps it is an after-the-setup test to confirm SGX indeed is available. If so, wording needs to change.
## Expected results
N/A
## Actual results
N/A

**Comment by dimakuv** [comment]
You probably mean https://gramine.readthedocs.io/en/latest/quickstart.html#quick-start-with-sgx-support ? (Note that you pasted the link to the old "Graphene" documentation, we now renamed Graphene to Gramine and thus new documentation is under the new "Gramine" link.)

Indeed, we have `Ensure that Intel SGX is enabled on your platform using is_sgx_available` sentence there. The `is_sgx_available` command is wrong -- it is actually `is-sgx-available` (dashes, not underscores). @vijaydhanraj Could you also fix this occurence in your PR #198 ?

**Comment by dimakuv** [comment]
Actually, the question raised by @mkbhanda is interesting. We indeed can use `is-sgx-available` utility only **after** we install Gramine. At the same time, in Step 1 of https://gramine.readthedocs.io/en/latest/quickstart.html#quick-start-with-sgx-support, we ask users to check whether this machine supports SGX at all, with the help of `is-sgx-available` (**before** installing Gramine).

How do we get out of this loop? The end user probably wants to first check SGX status on her machine with this tool, but for this the user needs to install Gramine-SGX, but Gramine-SGX doesn't make sense to be installed on a machine without SGX... @woju @pwmarcz Is there a way to "pre-install" `is-sgx-available` in a separate step?

**Comment by pwmarcz** [comment]
I assume this is about users building Gramine from source, since we're talking about the quickstart guide. 

The `is-sgx-available` command is single-file C++ with no dependencies on external libraries. So maybe we could replace step 1 with `g++ .../is_sgx_available.cpp -o is-sgx-available` and then running it.

Alternatively, we could make a shell script that compiles and runs it.

Another solution would be not to ask user to run `is-sgx-available` in this step, but to install and run the `cpuid` utility, which supports SGX since 2016.

**Comment by dimakuv** [comment]
I like the idea of just checking SGX using `cpuid | grep sgx`. Yes, maybe we should replace that particular description in Step 1 from `is-sgx-available` to `cpuid`.
