### ISSUE TITLE
Deprecate IAS API v3 and `ias_request` tool

### ISSUE THREAD

**Issue by woju** [gramineproject/gramine#22]
IAS API v3 (which is currently used by attestation utilities in `/Pal/**/Linux-SGX/tools/*`) is undocumented as of this writing. The documentation describes only v4 API: https://api.trustedservices.intel.com/documents/sgx-attestation-api-spec.pdf.

The `ias_request` tool needs not to be written in C, I wrote `graphene-ias-query` in Python as a wrapper of a simple library (`graphenelibos.ias`). When `graphene-ias-query` reaches functional parity with `ias_request`, the latter might be removed.

**Comment by boryspoplawski** [comment]
@dimakuv is this still relevant after v1.2?

**Comment by dimakuv** [comment]
The deprecation of IAS API v3 was done in this PR: https://github.com/gramineproject/gramine/pull/453

The request to rewrite our IAS tools from C to Python were **not** done. I don't think this has any high priority. The tools work fine. By the way, the tools were renamed at some point, and their current names are `gramine-sgx-ias-request`, `gramine-sgx-ias-verify-report`.

Since the main part of this issue was done (v3 -> v4), I'm closing this issue.
