### ISSUE TITLE
Error in Pytorch.manifest: toml.decoder.TomlDecodeError: Duplicate keys!

### ISSUE THREAD

**Issue by saruvig** [gramineproject/gramine#233]
Hi,

I am trying to run a new example in gramine running on Azure VM with PyTorch. I am using the following python.manifest.template. I followed the manifest template of pytorch in the graphene git (https://github.com/gramineproject/graphene/blob/master/Examples/pytorch/pytorch.manifest.template)

This is the manifest I am trying to run:

# PyTorch manifest template

loader.preload = "file:{{ gramine.libos }}"
libos.entrypoint = "{{ entrypoint }}"
loader.log_level = "{{ log_level }}"

loader.env.LD_LIBRARY_PATH = "/lib:/usr/lib:{{ arch_libdir }}:/usr/{{ arch_libdir }}"

loader.insecure__use_cmdline_argv = true
loader.insecure__use_host_env = true

loader.pal_internal_mem_size = "128M"

fs.mount.lib.type = "chroot"
fs.mount.lib.path = "/lib"
fs.mount.lib.uri = "file:{{ gramine.runtimedir() }}/"

fs.mount.lib2.type = "chroot"
fs.mount.lib2.path = "{{ arch_libdir }}"
fs.mount.lib2.uri = "file:{{ arch_libdir }}"

fs.mount.usr.type = "chroot"
fs.mount.usr.path = "/usr"
fs.mount.usr.uri = "file:/usr"

fs.mount.etc.type = "chroot"
fs.mount.etc.path = "/etc"
fs.mount.etc.uri = "file:/etc"

fs.mount.tmp.type = "chroot"
fs.mount.tmp.path = "/tmp"
fs.mount.tmp.uri = "file:/tmp"

fs.mount.pip.type = "chroot"
fs.mount.pip.path = "{{ env.HOME }}/.local/lib"
fs.mount.pip.uri = "file:{{ env.HOME }}/.local/lib"

sgx.nonpie_binary = true
sgx.enclave_size = "16G"
sgx.thread_num = 256

sgx.trusted_files = [
	"file:{{ entrypoint }}",
	"file:{{ gramine.runtimedir() }}/",
	"file:{{ arch_libdir }}/",
	"file:/usr/{{ arch_libdir }}/",
	"file:{{ python.stdlib }}/",
	"file:{{ python.distlib }}/",
	"file:{{ env.HOME }}/.local/lib/",
	"file:{{python.get_path('stdlib', vars={'installed_base': '/usr/local'}) }}",
	"file:scripts/",
    "file:/etc/mime.types",
    "file:/etc/default/apport",
 ]

sgx.allowed_files = [
 "file:/tmp",
 "file:/etc/apt/apt.conf.d",
 "file:/etc/apt/apt.conf",
 "file:/etc/default/apport",
 "file:/etc/nsswitch.conf",
 "file:/etc/group",
 "file:/etc/passwd",
 "file:/etc/host.conf",
 "file:/etc/hosts",
 "file:/etc/gai.conf",
 "file:/etc/resolv.conf",
 "file:/etc/fstab",
 "file:result.txt",
]

I was able to load gramine with sgx support successfully on my system. Tried the HelloWorld and Python examples from CI-Examples Folder.  Now I am trying to simple python scrip with gramine-sgx enabled

I get the following error when running make SGX =1
![image](https://user-images.githubusercontent.com/23428423/142611413-70e0ca6d-5e41-4769-b30d-98755d6f1617.png)

**Comment by dimakuv** [comment]
I don't see anything special in your manifest.template file. Are you sure you copy-pasted the latest `python.manifest.template` contents?

> I followed the manifest template of pytorch in the graphene git (https://github.com/gramineproject/graphene/blob/master/Examples/pytorch/pytorch.manifest.template)

Please don't use old Graphene repository. We have the latest PyTorch in the new repository: https://github.com/gramineproject/examples/blob/master/pytorch/pytorch.manifest.template

**Comment by saruvig** [comment]
As suggested, I shifted to the new repository code of PyTorch under Gramine. I am able to successfully build SGX now with the pytorch example but when I try to run it gets Killed.

**Comment by dimakuv** [comment]
`Killed` means that the Linux kernel noticed that RAM is dangereously close to fully used, and Linu invoked the OOM Killer (out of memory killer) to terminate the PyTorch Gramine process.

This is because your machine has too little RAM available.

Our PyTorch example has the enclave size of 16GB: 
https://github.com/gramineproject/examples/blob/ebc051be9dad032da789a27387c36db3cbadbc95/pytorch/pytorch.manifest.template#L46

PyTorch actually creates a child process, which means you will end up with 2 processes (parent and child) and thus 2 SGX enclaves, each 16GB in size. **This is a total of 32GB of consumed RAM.** Most probably you have less RAM than this requirement. That's why you see `Killed`.

The only real solution in this situation is to move to a machine with more RAM (or buy more RAM). See also similar issues here: https://github.com/gramineproject/gsc/issues/29#issuecomment-960534080

**Comment by saruvig** [comment]
yes my Azure VM has only 8 GB RAM. I changed the enclave side in the manifest to 2GB and am trying to run my own script on basic cifar with it. I added the script in the sgx_allowed files as "file:basic_cifar.py". I am able to build with SGX =1 , but while running get this error: SSL certification failed
![image](https://user-images.githubusercontent.com/23428423/142972621-2ebc80dd-e013-4447-8a10-f1a84850d9d3.png)


Am I missing some steps on how to add an allowed file?

**Comment by dimakuv** [comment]
> Am I missing some steps on how to add an allowed file?

Why do you think the error is about the allowed files? The error happens during SSL/TLS handshake. Since we don't know what your application does, it's hard to judge what's missing.

Please enable full Gramine logs: add/modify `loader.log_level = "all"` line in your manifest file, rebuild and run again. The log will give you additional information: what files Gramine tries to access (and whether Gramine fails or not), what connections Gramine tries to establish with which remote machines, what system calls Gramine executes, etc.

Please examine and analyze the log carefully. Typically, it is easy to spot the problematic place, and fix it in the manifest file.
