### ISSUE TITLE
Stress-ng open syscall test failing with assert fd < handle_map->fd_size on RHEL and CentOS

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gramine#28]
## Description of the problem

On RHEL and CentOS, stress-ng open syscall test is failing with the following errors:

`[P1:shim] error: Child process (vmid: 0x84) got disconnected
[P124:T124:stress-ng] assert failed ../LibOS/shim/src/bookkeep/shim_handle.c:419 fd < handle_map->fd_size`

Complete log file is attached below: 
[stress-ng_open_rhel.txt](https://github.com/gramineproject/gramine/files/7151263/stress-ng_open_rhel.txt)

## Steps to reproduce

`graphene-direct stress-ng --open 0 --timeout 60s --verbose`

**Comment by dimakuv** [comment]
I debugged it, and the reason is that this particular workload creates **a lot of** file descriptors (up to 100,000). This seems to be normal for `stress-ng` application.

However, in Gramine we have this: https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/LibOS/shim/include/shim_types.h#L341

Because `FDTYPE` is 16-bit in size, it can only count 65536 FDs. This leads to an implicit overflow and truncation here: https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/LibOS/shim/src/bookkeep/shim_handle.c#L576

Note that `fd_size` is of type `FDTYPE`: https://github.com/gramineproject/gramine/blob/74420be3a01d82415b36f142f5e52c87385befdd/LibOS/shim/include/shim_handle.h#L270

And that's how we bump into this assert: https://github.com/gramineproject/gramine/blob/40e942db6b02555cf2414f20bbd313b63f50e400/LibOS/shim/src/bookkeep/shim_handle.c#L419

(`handle_map->fd_size` was truncated to the max 16-bit value, so it is less that 32-bit `fd` value.)

**Proposed solution**: there is no reason to keep `FDTYPE` limited to 16 bits. I will change it to `uint32_t` and I'll remove `FDTYPE` user-defined type and will replace with explicit `uint32_t` everywhere in Gramine codebase. (Actually, we should do the same with `IDTYPE` but at least this one doesn't break anything.)

**Comment by jinengandhi-intel** [comment]
Dmitrii, any reason why this is triggered only on Cent and not on Ubuntu?

**Comment by dimakuv** [comment]
Good question. My assumption is that CentOS requires more files to be opened (and thus more FDs to be used)? Something like this.
