### ISSUE TITLE
How to write to `/dev/tty`?

### ISSUE THREAD

**Issue by lead4good** [gramineproject/gramine#303]
I am trying to run PHP with gramine-sgx (within a container).
PHP is trying to log errors to `/proc/self/fd/2` which is a symlink to `/dev/tty`, and `/dev/tty` has permission bits `000` set, which leads to a permission denied whenever PHP tries to log an error:
```
echo error > /proc/self/fd/2
/bin/bash: line 2: /proc/self/fd/2: Permission denied

ls -l /proc/self/fd/2
ls: /proc/self/fd/2: Function not implemented
lrwxrwxrwx 1 root root 0 Jan  1  1970 /proc/self/fd/2 -> /dev/tty

ls -alh /dev/tty
ls: /dev/tty: Function not implemented
c--------- 1 root root 0, 0 Jan  1  1970 /dev/tty
```
Any suggestions on how to make this work?

**Comment by dimakuv** [comment]
@lead4good This will be fixed by this PR: https://github.com/gramineproject/gramine/pull/297/commits. Check the very first commit of this PR. So I think, it should be fixed when this PR is merged (early next January, I guess).

**Comment by dimakuv** [comment]
@pwmarcz Is my understanding correct? If yes, could you add in your PR 297 description that it will fix this issue?

**Comment by pwmarcz** [comment]
My PR fixes permissions, but there's still something broken:

```
$ gramine-direct busybox sh -c 'echo foo>/proc/self/fd/2'
sh: can't create /proc/self/fd/2: Permission denied
```

(BTW, using `>>` works regardless of permissions).

The problematic call is:
```
[P1:T1:busybox] trace: ---- shim_openat(AT_FDCWD, "/proc/self/fd/2", O_WRONLY|O_CREAT|O_TRUNC, 0666) = -13   (EACCES)
```

Apparently this is because of `O_TRUNC`. Linux ignores it, but Gramine translates it to a call to `DkStreamSetLength` which fails on the `dev:tty` device. Probably it should be ignored inside PAL (or translated to `ftruncate()`?).

Unfortunately I can't promise to fix it in the near future, but I can review a fix if someone else does it.

**Comment by jkr0103** [comment]
Please assign to me for the fix.
