### ISSUE TITLE
Process CPU Clock not implemented

### ISSUE THREAD

**Issue by SoulKa** [gramineproject/gramine#327]
## Description of the problem

I need to measure the CPU time consumption of my program running in Gramine (including CPU time of the Gramine LibOS). However, as implemented in `shim_time.c` ([Code](https://github.com/gramineproject/gramine/blob/175b1867cbe81250e75d5b8b9b35ba0530a37e7f/LibOS/shim/src/sys/shim_time.c#L56-L76)), the clock ID parameter is always ignored and only the system clock is returned. There is no warning if the user program calls `clock_gettime()` with the clock ID `CLOCK_PROCESS_CPUTIME_ID`, even though it is not implemented.

## Steps to reproduce

1. Write a program in C or C++
2. Call `clock_gettime()` with the clock ID `CLOCK_PROCESS_CPUTIME_ID` in the Code
3. Get the system clock instead of the process CPU time

### PLEASE ENSURE THAT THE ISSUE REPRODUCES ON THE CURRENT MASTER BRANCH ###

I'm using the current release (Gramine 1.0). The code is still present in the current master branch.

## Expected results

The process CPU time should be returned, or a warning or error should be thrown that indicates that the clock `CLOCK_PROCESS_CPUTIME_ID` is not implemented.

## Actual results

The system time is returned and no warning is shown.

**Comment by dimakuv** [comment]
We chose to *not* implement different types of clocks in Gramine, because the clock values may be maliciously modified by the attacker, and so there was little incentive for us to try to implement e.g. `CLOCK_PROCESS_CPUTIME_ID`.

But I agree that we simply silently return `CLOCK_REALTIME` always. I believe that at least a one-time warning when the user asks for `CLOCK_PROCESS_CPUTIME_ID` or `CLOCK_THREAD_CPUTIME_ID` should be written by Gramine.

@SoulKa Is a warning message gonna be enough for your purposes?

**Comment by SoulKa** [comment]
It is not helping for my case as I need to measure the CPU time consumed for a program running inside Gramine SGX. But I think it is enough to resolve this inconsistency and close this issue.

**Comment by mkow** [comment]
There's no trusted time inside enclaves (because the CPU itself doesn't know the time, and other PC components aren't trusted), so the easiest solution will most likely be just measuring the amount of computation finished instead of CPU time used (I'm assuming you need this for accounting purposes, so it has to be non-alterable by the enclave host). Another solution would be to periodically connect to some trusted (maybe even your own?) time server over a cert-pinned TLS.

**Comment by SoulKa** [comment]
Actually, I'm comparing the CPU consumption of various SGX runtimes using the asynchronous syscall interface. For Gramine this is achieved using the "rpc-threads". I expected the `clock_gettime()` call to be forwarded to the RPC threads in Gramine. For other SGX runtimes such as Occlum, the `clock_gettime()` syscall using the `CLOCK_PROCESS_CPUTIME_ID` clock actually returns the consumed CPU time of the whole process (not including the workers in this case, since Occlum runs several processes).

The only alternative I could think of is using the `/proc/pid_of_gramine_loader/stat` to get the consumed CPU time of Gramine. But this would be quite inaccurate.

**Comment by boryspoplawski** [comment]
All we could do in Gramine is pass time info from untrusted host OS, which is by design insecure and can be easily done outside of Gramine (either by some wrapper, modifying untrusted Gramine loader or injecting some shared library into the process, etc.).
For testing purposes getting untrusted time should be enough and actually more accurate and reliable.

**Comment by SoulKa** [comment]
I finally managed to get the CPU time from inside Gramine by creating a softlink to `/proc/pid_of_gramine_loader/stat` to `/tmp/stat` and adding `/tmp/stat` to the list of allowed files and mounting the host `/tmp` FS. It is insecure, but this is completely about performance measuring. Thank you for your suggestions!

**Comment by mkow** [comment]
Seems that @SoulKa's problem was resolved, but let's keep this issue open until we fix the following:

> [...] we simply silently return `CLOCK_REALTIME` always. I believe that at least a one-time warning when the user asks for `CLOCK_PROCESS_CPUTIME_ID` or `CLOCK_THREAD_CPUTIME_ID` should be written by Gramine.

Any volunteer? ;)
