### ISSUE TITLE
[LibOS] Emulate mlock/mlock2/munlock/etc family of syscalls

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#48]
Implement mlock, mlock2, munlock, mlockall, munlockall (lock and unlock memory). These can be stubbed easily by always returning success (Graphene cannot guarantee that the host OS will perform lock/unlock anyway, and a malicious OS will swap pages anyway).

This will allow to re-enable more LTP tests such as mincore02.

**Comment by lead4good** [comment]
@Nirusu Have you been able to progress on running .NET within gramine?

**Comment by Nirusu** [comment]
@lead4good Have not really done anything ever since my last comment on this...
Generally, I _think_ with the changes I described above (stubbing `mlock`, `munlock`) and changing the GC configuration should get at least some "Hello World" kind of application running. I never tried anything besides this GCP microservice demo application, however since this was already part of the user code and not the runtime, I think in general the runtime works.

However, I am not sure to which extent you can get .NET applications running, as this might depend on which syscalls are used and if they are implemented by Gramine. I could image a speciality with .NET is that Microsoft tries to replicate Windows-like behavior under Linux and thus use "untypical" system calls which Gramine has not implemented since they have not been a priority... Cannot really say the exact reason, though without taking a deep-dive into it. I am not really familiar with how .NET works under Linux under the hood. I just went by trial and error myself.

**Comment by lead4good** [comment]
@Nirusu Thanks again for your summary regarding .NET bringup in gramine.
As suggested in this issue I've implemented the mlock family of syscalls to just return success (PR merged), which brought me to the OOM issue:
```
Failed to create CoreCLR, HRESULT: 0x8007000E
```
I haven't been able to fix the OOM error by switching the garbage collector like you described, however limiting the GC heap by setting the `COMPlus_GCHeapHardLimit` env variable did the trick for me. Note that I had to set a significant lower amount compared to the enclaves_size. With 1GB of enclave size I could set the GC heap size to 64M. Keep in mind that `COMPlus_GCHeapHardLimit` accepts numbers in hex format.
This brings us to the FileSystemWatcher which we actually do not need if `DOTNET_USE_POLLING_FILE_WATCHER` is enabled. This only works since .NET 5.0, as there is still a bug in the older dotnet-core runtime which tries to start the FileSystemWatcher even if the flag is set, see https://github.com/dotnet/runtime/pull/41426.
With the above I was able to run a simple ASP.NET application within gramine successfully.

@dimakuv I think #309 fixes this issue and it can be closed.

**Comment by dimakuv** [comment]
Thanks @lead4good and @Nirusu for this effort! Great to see .NET applications running (with caveats).

> With 1GB of enclave size I could set the GC heap size to 64M.

Just a note: from my experience, 1GB is not enough for garbage-collector-based runtimes (like Python, Go, Java and .NET). I observed that many real-world workloads require at least 4-8GBs, and in many cases we set the enclave size to 16-32GB.

Since this particular issue (missing support of `mlock` family of syscalls) was resolved via #309, I'm closing this issue.
