### ISSUE TITLE
Unable to mount files with fs.mounts

### ISSUE THREAD

**Issue by chigarovae** [gramineproject/gramine#582]
Hi! I'm currently attempting to mount some folders with fs.mounts. Here's the corresponfing part of the manifest:

```
fs.mounts = [
  { path = "/native-datasets", uri = "file:/mnt/datasets-update/" },
  { path = "/datasets", uri = "file:/mnt/datasets-volume/" },
  { path = "/private", uri = "file:/mnt/private/" },
  { path = "/certs/ids.key", uri = "file:/mnt/certs/ids.key" },
  { path = "/worker_instance_name", uri = "file:/etc/hostname" }
]
```

But when launching the image, i'm getting this:

```
[::] debug: Creating pipe: pipe.srv:f662f2a6c8ecdf59be6be3412f49bb0b3f19faa78af13091533bd805c989adb6
[P1:T1:] debug: mounting "file:/mnt/datasets-update/" (chroot) under /native-datasets
[P1:T1:] warning: error looking up mount root /native-datasets: -2
[P1:T1:] error: error mounting "file:/mnt/datasets-update/" (chroot) under /native-datasets: -2
[P1:T1:] error: Error during shim_init() in init_mount (-2)
debug: DkProcessExit: Returning exit code 2
```

Tried array syntax:
```
[[fs.mounts]]
type = "chroot"
path = "/native-datasets"
uri  = "file:/mnt/datasets-update/"
```
Result was the same. What am i doing wrong? Image works fine without mounting.

**Comment by mkow** [comment]
-2 is `ENOENT`, are you sure you have `/mnt/datasets-update/` on the host?

**Comment by dimakuv** [comment]
+1 to @mkow. A bit of explanation here. The manifest syntax like this:
```
  { path = "/native-datasets", uri = "file:/mnt/datasets-update/" },
```

tells Gramine to create (mount) an in-Gramine-visible path `/native-datasets/` and make it "mirror" the contents of the host path `/mnt/datasets-update/`.

So the host path `/mnt/datasets-update/` should be already created on the host, with correct permissions (such that the Gramine process has access to this directory and its contents).

It looks like you're using a Docker image, and this `/mnt/datasets-update/` path is a mounted volume in your Docker image. Please make sure you're actually mounting this path when starting the Docker container, otherwise Gramine tries and fails to search this mounted volume (for Gramine, the files inside the Docker container become the "host" files).

**Comment by chigarovae** [comment]
@mkow @dimakuv Thanks for yor response! I assumed that uri should exist on the host machine, didn't know that docker container is considered as a host by Gramine) Will try it, thanks once again.
