### ISSUE TITLE
Question on Paper "Practical Implications of Graphene-SGX"

### ISSUE THREAD

**Issue by xanderdunn** [gramineproject/gramine#595]
The ease of use of using unmodified programs on SGX via Gramine is very alluring given how difficult it is to port libraries and applications into SGX with the Intel SGX SDK / OpenEnclave paradigm of ocall/ecall EDL porting. However, we have some concerns about the size of the trusted computing base and we encountered this paper from 2019: The paper [Practical Implications of Graphene-SGX](https://rp.os3.nl/2018-2019/p76/report.pdf) writes that Graphene's LibOS may make applications vulnerable through use of the system clock and by reading environment variables that the developer may not be aware of. The paper recommends against using Gramine/Graphene for production applications. In the three years since the paper, have these issues been addressed, is it considered production-worthy at this point? 

Thanks!

**Comment by boryspoplawski** [comment]
Please don't use GitHub issues for general support (see the information in the issue template), we use issues to keep track of bugs in Gramine.
If you need support then write an email to [users@gramineproject.io](mailto:users@gramineproject.io) or join our Gitter (https://gitter.im/gramineproject/community).

**Comment by xanderdunn** [comment]
The library making silent use of the system clock or silently reading environment variables the developer isn’t aware of counts as a set of security bugs. It should be publicly documented how Gramine handles this. I will forward it to the email address you listed and post the response I get here.

**Comment by dimakuv** [comment]
[ I will post my answer here since other users can stumble upon this issue. Since this is a legit question asked by many users, it is better to duplicate our answer here. ]

> Graphene's LibOS may make applications vulnerable through use of the system clock...

This issue is *partially* addressed. Gramine checks that the clock never goes backwards during the lifetime of the SGX enclave. However, the malicious OS can "slow down" the time, or the malicious OS can pick a starting datetime way in the past (e.g., the malicious OS can set the clock to 1. January 1970, and Gramine / Intel SGX have no way of finding this out).

See the corresponding code here: https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/Pal/src/host/Linux-SGX/enclave_ocalls.c#L1501-1505

Some advice how to resolve this: The application inside Gramine should be aware of such possibly malicious behavior. The application should either only use *relative time*, or fetch the trusted time from some trusted source on the Internet.

> ...and by reading environment variables that the developer may not be aware of

This issue was fixed a long time ago. Gramine is configured using the manifest file. And there is a special set of manifest knobs to tweak the environment-variables behavior, see our docs: https://gramine.readthedocs.io/en/latest/manifest-syntax.html#environment-variables

Gramine by default doesn't read the environment variables from the host. Only a set of explicitly specified envvars is hard-coded / forwarded from the host. Gramine can read all envvars from the host, but this is obviously insecure and can only be enabled with the explicit `loader.insecure__use_host_env = true` option.
