### ISSUE TITLE
Does gramine support golang application?

### ISSUE THREAD

**Issue by bronzeMe** [gramineproject/gramine#596]
## Description of the problem

- As we know, golang has its own syscall wrapper implementation, it does not use glibc to invoke system call
- So, when a golang application invokes a system call (e.g., open/write a file), the gramine libos cannot catch this invocation , then this golang application will directly issue a system  call to the host kernel inside the enclave.
- The question is:
- Q1: Has gramine solved this problem will already?
- Q2: If not, how do we patch the gramine to support running native golang application, the patch may be similar to [occlum-go.](https://github.com/occlum/occlum/blob/master/tools/toolchains/golang/adapt-golang1.16.3-to-occlum.patch)

Thanks.

**Comment by dimakuv** [comment]
> Q1: Has gramine solved this problem will already?

Yes, this problem was solved.

1. For `gramine-sgx` (in SGX mode), every raw `syscall` instruction ("direct invocation of system call") is trapped by the Intel SGX hardware and forwarded back to Gramine. Gramine emulates this `syscall` instruction by calling Gramine's syscall wrapper implementation.
2. For `gramine-direct` (non-SGX mode), Gramine setups the seccomp filter that catches all `syscall` instructions, traps them and forwards back to Gramine.

In case you are interested, see these source codes:
1. https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/Pal/src/host/Linux-SGX/db_exception.c#L166
2. https://github.com/gramineproject/gramine/blob/e8735ea06cc6b27932e97cc8173fa492b6f8a488/Pal/src/host/Linux/db_exception.c#L228

> Q2: If not, how do we patch the gramine to support running native golang application, the patch may be similar to [occlum-go.](https://github.com/occlum/occlum/blob/master/tools/toolchains/golang/adapt-golang1.16.3-to-occlum.patch)

Thanks for providing this link. It is interesting, and yes, Go applications that are compiled against this patched Go compiler will not issue raw `syscall` instructions, but instead they will directly call into the SGX runtime (Occlum in this case). However, the Gramine team is still debating whether such approach is maintainable -- users do *not* like to recompile their applications, and also providing patches for each version of the Go compiler requires a lot of effort.

**Comment by bronzeMe** [comment]
@dimakuv ,Thank you so much ! This detail reply is so helpful!
Actually, patching each version of Go compiler is not easy. 
But I guess the method (patching go compiler)  maybe more fast  than gramine's current strategy (through  handling exception) ?
Thanks a lot.

**Comment by dimakuv** [comment]
> But I guess the method (patching go compiler) maybe more fast than gramine's current strategy (through handling exception) ?

Yes, this is exactly the problem with the current approach of Gramine (trap-and-emulate, or as you call it "handling exceptions"). This current approach is slow, because trap-and-emulate is slow by definition.

So the Gramine team is looking at other options how to make Go applications run faster. Patching the Go compiler is one option...

**Comment by bronzeMe** [comment]
Hi @dimakuv, There is a project [GrapheneSGX-Golang-Support-and-Enhancement](https://github.com/intel/GrapheneSGX-Golang-Support-and-Enhancement/tree/20190715-golang/LibOS/libs/golang) which provides scripts to  automatically redirect a go executable file's raw syscall to graphene's syscall wrapper, but it is not compatible with gramine.
