### ISSUE TITLE
More flexible she bang in python scripts

### ISSUE THREAD

**Issue by rafariossaa** [gramineproject/gramine#804]
## Description of the problem

The she bang in the python scripts is pointing to the python installation at system level and makes it difficult to try to run the scripts in different python environments, or if you have a version at system level but wants to run it with other python in your system, other case could be with venvs.

A solution for this could be the following.
```diff
> #!/usr/bin/python3
---
< #!/usr/bin/env python3
```
This will allow the scripts to use the python in the `PATH`

## Expected results

To be able to run the python scripts with other pythons

**Comment by boryspoplawski** [comment]
https://github.com/gramineproject/gramine/pull/429

**Comment by dimakuv** [comment]
I'd say the most relevant and concise explanation is here: https://gramine.readthedocs.io/en/latest/devel/coding-style.html#python

> The she bang in the python scripts is pointing to the python installation at system level and makes it difficult to try to run the scripts in different python environments, or if you have a version at system level but wants to run it with other python in your system, other case could be with venvs.

I believe there is a real problem here (with "virtual environments" of Python, e.g., `venv` and `conda`), but @rafariossaa could you explain a particular scenario where you hit this issue? Gramine probably *should* have some modifications to work with virtual environments, we just didn't have a concrete example for this.

**Comment by rafariossaa** [comment]
Hi,
  Sorry for the delay.
  In this case, I have a python installation at system level but for the user that runs gramine I have a newer version of python. I am not using venv.

**Comment by dimakuv** [comment]
> In this case, I have a python installation at system level but for the user that runs gramine I have a newer version of python.

Why do you need a newer version of Python for the user? What I'm looking for is a specific scenario where this is necessary, and our current reliance on `/usr/bin/python3` breaks Gramine workflows.
