### ISSUE TITLE
Error when running the example helloworld

### ISSUE THREAD

**Issue by deliciousdish** [gramineproject/gramine#865]
I follow the instrunctions in [QuickStart](https://gramine.readthedocs.io/en/latest/quickstart.html) on ubuntu 20.04, when running "gramine-direct helloworld", i got the following error:
```
error: PAL failed at ../../Pal/src/db_main.c:pal_main:457 (exitcode = 4, reason=argv handling wasn't configured in the manifest, but cmdline arguments were specified.)
```
make SGX=1 and run "gramine-sgx helloworld" got the same error.
How to solve this issue?

**Comment by boryspoplawski** [comment]
1. Please read and use issues template, it's there for a reason.
2. The link you've posted has a caution banner at the top. Please read it.
3. Assuming you've installed Gramine from apt, you need to checkout `v1.2` tag in repo in order to get examples compatible with that version (latest version from apt).
